docs: add descriptions for scan_block_size and scan_yield_interval
project-tsurugi/tsurugidb pull request #104
Opened 2024-10-11 01:40 UTC by YoshiakiNishimura

https://github.com/project-tsurugi/tsurugi-issues/issues/706

2024-10-11 01:56 UTC, kuron99 commented on docs/config-parameters.md
> +| `scan_block_size` | Integer | The scan operator processes either the entire table or a specific range of data. When the range to be processed is large, the processing thread may become unresponsive
説明の最初のセンテンスは「設定した値が何か」ということを説明する文にしてください。他のパラメータもその形式で説明を始めていると思います。例えば `scan_block_size` の場合は `the maximum number of records processed before yielding to other tasks` をここに持ってくるのがいいです。

2024-10-11 01:57 UTC, kuron99 commented on docs/config-parameters.md
> +| `scan_block_size` | Integer | The scan operator processes either the entire table or a specific range of data. When the range to be processed is large, the processing thread may become unresponsive
0を指定することでyieldをしないようにすることも可能であることも記述してください。

2024-10-11 01:57 UTC, kuron99 commented on docs/config-parameters.md
> +| `scan_yield_interval` | Integer | Similar to scan_block_size, the scan_yield_interval parameter also imposes a limit on the records processed by the scan operator, but this limit is based on time i
ここも上と同様に最初のセンテンスで `scan_yield_interval` が何なのかの概要を記してください。

2024-10-11 02:08 UTC, kuron99 commented on docs/config-parameters.md
> +| `scan_yield_interval` | Integer | Similar to scan_block_size, the scan_yield_interval parameter also imposes a limit on the records processed by the scan operator, but this limit is based on time i
この説明だと`scan_block_size` と `scan_yield_interval` の両方が設定された場合にどう動くのか明確でないのと、実装では`scan_block_size`が設定されている場合に`scan_yield_interval`が使われているので、 `scan_block_size takes precedence over scan_yield_interval` は正しくないと思います。両者が設定された際にどう動くか、という点を詳細に記したほうがいいのではないでしょうか。

2024-10-11 02:10 UTC, kuron99 commented on docs/config-parameters.md
> +| `scan_yield_interval` | Integer | Similar to scan_block_size, the scan_yield_interval parameter also imposes a limit on the records processed by the scan operator, but this limit is based on time i
`scan_yield_interval` についてもdisableするために設定する値があれば記述してください。

2024-10-11 02:10 UTC, kuron99 requested changes
コメントしました。レビュー完了で一旦戻します。

2024-10-11 03:41 UTC, YoshiakiNishimura commented
@kuron99  指摘反映しました

2024-10-11 08:18 UTC, kuron99 commented on docs/config-parameters.md
> +| `scan_yield_interval` | Integer | The maximum time of scan operator records processed before yielding to other tasks. The default limit is 1 millisecond. To disable this option, set the correspondi
最初のセンテンスに単位も明記してください。あと、`The maximum time of scan operator records processed` だと指定するのが `records` なのか `time`なのかがあやふやではないですか。
あと `maximum time` が正しいでしょうか？ 最低この時間過ぎていなければyieldが行われない、という動きだと思うのでどちらかというと `minimum time` のほうが近そう？

2024-10-11 08:20 UTC, kuron99 commented on docs/config-parameters.md
> +| `scan_yield_interval` | Integer | The maximum time of scan operator records processed before yielding to other tasks. The default limit is 1 millisecond. To disable this option, set the correspondi
`To disable this option,`のところは scan_yield_intervalに 0 を指定すれば時間区切りによるyield判定を行わないことになるのでそういう記述でもよさそうに思います。

それと別に、scan_block_size が0以外のときだけscan_yield_intervalも有効になる、という記述を追加するのがいいのではないでしょうか。

2024-10-11 08:20 UTC, kuron99 requested changes
コメントしました

2024-10-11 08:49 UTC, YoshiakiNishimura commented on docs/config-parameters.md
> +| `scan_yield_interval` | Integer | The maximum time of scan operator records processed before yielding to other tasks. The default limit is 1 millisecond. To disable this option, set the correspondi
before yielding to other tasksなのでmaximumです

単位は以下の通り前にもっていきます

修正前
The maximum time of scan operator records processed before yielding to other tasks. The default limit is 1 millisecond.
修正後
The maximum millisecond time of scan operator records processed before yielding to other tasks. The default limit is 1.

2024-10-11 09:39 UTC, YoshiakiNishimura commented on docs/config-parameters.md
> +| `scan_yield_interval` | Integer | The maximum time of scan operator records processed before yielding to other tasks. The default limit is 1 millisecond. To disable this option, set the correspondi
誤解を与える文章なので全面改訂しました。
要旨
scan_yield_intervalに=0は時間による分割は行わない(けどscan_block_sizeの設定は生きる)、
分割自体止めたい場合はscan_block_size=0
scan_yield_interval使う場合はscan_block_sizeを既定値にすることを推奨します

The maximum millisecond time of scan operator records processed before yielding to other tasks. The default limit is 1. If the value of this option is set to 0, the decision to split will rely solely on the value of scan_block_size. When using this option, it is recommended to keep the scan_block_size at its default value. If the scan_block_size is set to an extremely large value, the actual split occur after a time that significantly exceeds the specified value of this option.

2024-10-11 09:41 UTC, kuron99 commented on docs/config-parameters.md
> +| `scan_yield_interval` | Integer | The maximum time of scan operator records processed before yielding to other tasks. The default limit is 1 millisecond. To disable this option, set the correspondi
少なくとも指定された時間が経過しなければ条件がtrueにならなくてyield処理にうつらないので、minimumかと思ったのですが、それでいうとscan_block_sizeも同じ話ですね。

"records processed"という名詞句の掛り方がまだ不自然な感じがするのですが、下記のような感じでどうでしょう？
The maximum millisecond time of scan operator processing records before yielding to other tasks.

2024-10-15 00:47 UTC, kuron99 commented on docs/config-parameters.md
> +| `scan_yield_interval` | Integer | The maximum time of scan operator records processed before yielding to other tasks. The default limit is 1 millisecond. To disable this option, set the correspondi
いいと思います。最初の文については https://github.com/project-tsurugi/tsurugidb/pull/104#discussion_r1796706127 の適用も検討してみてください。

2024-11-12 05:47 UTC, kuron99 approved these changes
修正確認しました。問題ありません。

2024-11-12 12:09 UTC, merged